### ISSUE TITLE
Doesn't build

### ISSUE THREAD

**Issue by seojiwon** [DIVERSIFY-project/syringe#3]
I tried to build the project with maven, but get the following error:

[ERROR] Failed to execute goal on project syringe-reader: Could not resolve dependencies for project fr.inria.diversify:syringe-reader:jar:1.0.0: The following artifacts could not be resolved: fr.inria.diversify:build-system:jar:1.0-SNAPSHOT, fr.inria.gforge.spoon:spoon-core:jar:3.0-SNAPSHOT: Could not find artifact fr.inria.diversify:build-system:jar:1.0-SNAPSHOT -> [Help 1]

I tried with different version number of spoon-core and build-system, but all did not work.

**Comment by marcelinorc** [comment]
Hey seojiwon, sorry for this answer sooooo delayed... Please download and maven install the dependency from here https://github.com/DIVERSIFY-project/maven_build_sys
